#!/usr/bin/env bun
/// Where MySQL's own answers moved between supported majors.
///
/// Pintail answers as MySQL 8.4 does. Replaying the same suite, with the same
/// binary, against an 8.0 oracle and an 8.4 oracle and comparing the two exact
/// sets separates three things: statements both majors answer as Pintail does,
/// statements only 8.4 answers that way (MySQL changed the answer, or 8.0
/// refuses the statement), and statements only 8.0 answers that way - where
/// Pintail follows the older major, which is either a deliberate 8.0
/// compatibility or a divergence from the version it claims.
///
/// Usage: bun run scripts/archaeology/version-skew.ts
///   reads  validate-out/mtr/exact.json, validate-out/mtr/exact-mysql80.json
///   writes docs/mysql-parity/version-skew.md
import { readFileSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'

const root = resolve(import.meta.dir, '..', '..')

interface ExactSet {
  oracle: string
  files: Record<string, string[]>
}

export interface Skew {
  file: string
  both: number
  newerOnly: number
  olderOnly: number
}

export function skew(newer: ExactSet, older: ExactSet): Skew[] {
  const files = new Set([...Object.keys(newer.files), ...Object.keys(older.files)])
  return [...files]
    .map((file) => {
      const a = new Set(newer.files[file] ?? [])
      const b = new Set(older.files[file] ?? [])
      return {
        file,
        both: [...a].filter((id) => b.has(id)).length,
        newerOnly: [...a].filter((id) => !b.has(id)).length,
        olderOnly: [...b].filter((id) => !a.has(id)).length,
      }
    })
    .filter((row) => row.newerOnly || row.olderOnly)
    .sort((x, y) => y.newerOnly + y.olderOnly - (x.newerOnly + x.olderOnly) || x.file.localeCompare(y.file))
}

function main() {
  const read = (name: string) => JSON.parse(readFileSync(join(root, 'validate-out', 'mtr', name), 'utf8')) as ExactSet
  const newer = read('exact.json')
  const older = read('exact-mysql80.json')
  const rows = skew(newer, older)
  const total = (key: keyof Omit<Skew, 'file'>) => rows.reduce((n, r) => n + r[key], 0)
  const allBoth = Object.keys(newer.files).reduce(
    (n, file) => n + (newer.files[file] ?? []).filter((id) => (older.files[file] ?? []).includes(id)).length,
    0,
  )
  const lines = [
    '# Version skew in the upstream suite',
    '',
    'Generated by `bun run scripts/archaeology/version-skew.ts` from two replays of the MySQL main suite with',
    `one Pintail binary: oracle MySQL ${newer.oracle} and oracle MySQL ${older.oracle}.`,
    '',
    `${allBoth.toLocaleString()} statements match both majors. ${total('newerOnly').toLocaleString()} match only ${newer.oracle}: MySQL changed`,
    `the answer between majors, or ${older.oracle} refuses the statement. ${total('olderOnly').toLocaleString()} match only ${older.oracle}: Pintail`,
    `gives the older major's answer, which is a divergence from the version it follows unless it is recorded as`,
    'a deliberate compatibility.',
    '',
    `| File | Both | Only ${newer.oracle} | Only ${older.oracle} |`,
    '|---|---:|---:|---:|',
    ...rows.map((r) => `| ${r.file} | ${r.both} | ${r.newerOnly} | ${r.olderOnly} |`),
    '',
  ]
  writeFileSync(join(root, 'docs', 'mysql-parity', 'version-skew.md'), lines.join('\n'))
  console.log(`wrote docs/mysql-parity/version-skew.md: ${rows.length} files differ`)
}

if (import.meta.main) main()
