[package]
name = "pintail-store"
description = "From-scratch columnar storage engine for Pintail"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
fs2.workspace = true
lz4_flex.workspace = true
pintail-types.workspace = true
xxhash-rust.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
