[package]
name = "pintail-protocol"
description = "MySQL client/server wire protocol for Pintail"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
sha1.workspace = true
sha2.workspace = true
tokio = { workspace = true, features = ["io-util"] }

[lints]
workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "io-util"] }
rsa.workspace = true
rand_core06.workspace = true
sha1.workspace = true
