import { describe, expect, test } from 'bun:test'
import { capturedQueries, extractShapes, redactSql, sanitized, splitSql } from './bi-dogfood'

describe('BI dogfood capture', () => {
  test('splits SQL without treating quoted semicolons or comments as boundaries', () => {
    expect(splitSql("SELECT ';' AS value; -- keep going\nSELECT 2")).toEqual([
      "SELECT ';' AS value",
      '-- keep going\nSELECT 2',
    ])
  })

  test('reads JSONL and MySQL general-log text records', () => {
    const capture = [
      JSON.stringify({ command_type: 'Query', argument: 'SELECT 1' }),
      '2026-08-07T00:00:00\tapp\t12\t1\tQuery\tSHOW TABLES',
      JSON.stringify({ command_type: 'Connect', argument: 'ignored' }),
    ].join('\n')
    expect(capturedQueries(capture)).toEqual(['SELECT 1', 'SHOW TABLES'])
  })

  test('deduplicates literal variants while retaining one exact replay query', () => {
    const shapes = extractShapes("SELECT * FROM orders WHERE id = 10; SELECT * FROM orders WHERE id = 20")
    expect(shapes).toHaveLength(1)
    expect(shapes[0]).toMatchObject({
      query: 'SELECT * FROM orders WHERE id = 10',
      shape: 'SELECT * FROM orders WHERE id = ?',
      count: 2,
      class: 'read',
    })
  })

  test('classifies writes as ignored and redacts text, hex, and numeric literals', () => {
    const shapes = extractShapes([
      "UPDATE users SET email = 'secret@example.com' WHERE id = 7",
      'WITH doomed AS (SELECT id FROM users) DELETE FROM users WHERE id IN (SELECT id FROM doomed)',
      'SET GLOBAL max_connections = 100',
    ].join(';'))
    expect(shapes.every((shape) => shape.class === 'ignored')).toBe(true)
    expect(redactSql("SELECT 'secret', 42, 0xfeed, X'CAFE'")).toBe("SELECT '?', ?, ?, ?")
  })

  test('classifies comment-prefixed and CTE reads without replaying CTE writes', () => {
    const shapes = extractShapes([
      '-- generated by dashboard\nSELECT 1',
      'WITH visible AS (SELECT 1 AS id) SELECT id FROM visible',
      'WITH doomed AS (SELECT 1 AS id) DELETE FROM users WHERE id IN (SELECT id FROM doomed)',
    ].join(';'))
    expect(shapes.map((shape) => shape.class).sort()).toEqual(['ignored', 'read', 'read'])
  })

  test('sanitized reports never retain successful result values', () => {
    const [entry] = sanitized([{
      query: "SELECT email FROM users WHERE tenant_id = 'private'",
      shape: "SELECT email FROM users WHERE tenant_id = '?'",
      count: 1,
      class: 'read',
      status: 'match',
      mysql: { ok: true, fields: ['email'], rows: [['person@example.com']] },
      pintail: { ok: true, fields: ['email'], rows: [['person@example.com']] },
    }])
    expect(entry.query).toBe(entry.shape)
    expect(entry.mysql).toEqual({ ok: true, fields: ['email'], rowCount: 1 })
    expect(entry.pintail).toEqual({ ok: true, fields: ['email'], rowCount: 1 })
    expect(JSON.stringify(entry)).not.toContain('person@example.com')
    expect(JSON.stringify(entry)).not.toContain('private')
  })
})
