use super::{Column, DataType, KeyPart, OracleCase, PrimaryKey, StoredRow, TableSchema, Value};

pub const SQL: &str = "CREATE TABLE bounds (id BIGINT PRIMARY KEY, n BIGINT NULL, u BIGINT UNSIGNED NULL, whole DECIMAL(38,0) NULL, frac DECIMAL(20,3) NULL, approx DOUBLE NULL, txt VARCHAR(32) COLLATE utf8mb4_unicode_ci NULL, fixed CHAR(8) COLLATE utf8mb4_general_ci NULL, raw VARBINARY(16) NULL, day DATE NULL, dt0 DATETIME(0) NULL, dt3 DATETIME(3) NULL, dt6 DATETIME(6) NULL, clock TIME(6) NULL, stamp TIMESTAMP(6) NULL) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci; INSERT INTO bounds VALUES (1,-9223372036854775808,0,'99999999999999999999999999999999999999','-99.995',0.1,'','',X'','2000-02-29','2000-02-29 00:00:00','2000-02-29 00:00:00.125','2000-02-29 00:00:00.125001','-838:59:59.000000','2000-02-29 00:00:00.125001'),(2,-9007199254740993,1,'-99999999999999999999999999999999999999','-0.005',-0.5,'NULL','NULL',X'4e554c4c','2024-02-29','2024-02-29 00:00:00','2024-02-29 00:00:00.125','2024-02-29 00:00:00.125001','-100:00:00.000001','2024-02-29 00:00:00.125001'),(3,-1,9007199254740993,'-1','0.000',1.5,'a ','a',X'00','2024-03-31','2024-03-31 00:00:00','2024-03-31 00:00:00.125','2024-03-31 00:00:00.125001','-00:00:00.000001','2024-03-31 00:00:00.125001'),(4,0,9223372036854775808,'0','0.005',2.5,'a ','a ',X'ff','2024-11-03','2024-11-03 00:00:00','2024-11-03 00:00:00.125','2024-11-03 00:00:00.125001','00:00:00.000000','2024-11-03 00:00:00.125001'),(5,1,18446744073709551615,'1','1.500',-2.5,'é','é',X'fe','2025-01-01','2025-01-01 00:00:00','2025-01-01 00:00:00.125','2025-01-01 00:00:00.125001','00:00:00.000001','2025-01-01 00:00:00.125001'),(6,9007199254740993,NULL,'2','2.500',10000000000.0,'e\u{301}','e\u{301}',X'6109620a63','2025-12-31','2025-12-31 00:00:00','2025-12-31 00:00:00.125','2025-12-31 00:00:00.125001','100:00:00.000000','2025-12-31 00:00:00.125001'),(7,9223372036854775807,10,'3','99.995',-0.0,'a\tb\nc','x',X'6120','2038-01-19','2038-01-19 00:00:00','2038-01-19 00:00:00.125','2038-01-19 00:00:00.125001','838:59:59.000000','2038-01-19 00:00:00.125001'),(8,NULL,100,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);";

pub fn schema() -> TableSchema {
    TableSchema::new(
        1,
        vec![
            Column::new(1, "id", DataType::Int64, false),
            Column::new(2, "n", DataType::Int64, true),
            Column::new(3, "u", DataType::UInt64, true),
            Column::new(
                4,
                "whole",
                DataType::Decimal {
                    precision: 38,
                    scale: 0,
                },
                true,
            ),
            Column::new(
                5,
                "frac",
                DataType::Decimal {
                    precision: 20,
                    scale: 3,
                },
                true,
            ),
            Column::new(6, "approx", DataType::Float64, true),
            Column::new(7, "txt", DataType::Utf8, true)
                .with_collation(Some("utf8mb4_unicode_ci".into())),
            Column::new(8, "fixed", DataType::Utf8, true)
                .with_collation(Some("utf8mb4_general_ci".into())),
            Column::new(9, "raw", DataType::Binary, true),
            Column::new(10, "day", DataType::Date32, true),
            Column::new(11, "dt0", DataType::DateTime64 { fsp: 0 }, true),
            Column::new(12, "dt3", DataType::DateTime64 { fsp: 3 }, true),
            Column::new(13, "dt6", DataType::DateTime64 { fsp: 6 }, true),
            Column::new(14, "clock", DataType::Time64 { fsp: 6 }, true),
            Column::new(15, "stamp", DataType::DateTime64 { fsp: 6 }, true),
        ],
    )
    .expect("boundary schema")
}

#[allow(clippy::too_many_lines)]
pub fn rows() -> Vec<StoredRow> {
    vec![
        StoredRow::new(
            PrimaryKey::new(vec![KeyPart::Int64(1)]).expect("key"),
            vec![
                Value::Int64(1),
                Value::Int64(-9_223_372_036_854_775_808),
                Value::UInt64(0),
                Value::Utf8("99999999999999999999999999999999999999".into()),
                Value::Utf8("-99.995".into()),
                Value::float64(0.1),
                Value::Utf8(String::new()),
                Value::Utf8(String::new()),
                Value::Binary(vec![]),
                Value::Utf8("2000-02-29".into()),
                Value::Utf8("2000-02-29 00:00:00".into()),
                Value::Utf8("2000-02-29 00:00:00.125".into()),
                Value::Utf8("2000-02-29 00:00:00.125001".into()),
                Value::Utf8("-838:59:59.000000".into()),
                Value::Utf8("2000-02-29 00:00:00.125001".into()),
            ],
            1,
            false,
        ),
        StoredRow::new(
            PrimaryKey::new(vec![KeyPart::Int64(2)]).expect("key"),
            vec![
                Value::Int64(2),
                Value::Int64(-9_007_199_254_740_993),
                Value::UInt64(1),
                Value::Utf8("-99999999999999999999999999999999999999".into()),
                Value::Utf8("-0.005".into()),
                Value::float64(-0.5),
                Value::Utf8("NULL".into()),
                Value::Utf8("NULL".into()),
                Value::Binary(vec![78, 85, 76, 76]),
                Value::Utf8("2024-02-29".into()),
                Value::Utf8("2024-02-29 00:00:00".into()),
                Value::Utf8("2024-02-29 00:00:00.125".into()),
                Value::Utf8("2024-02-29 00:00:00.125001".into()),
                Value::Utf8("-100:00:00.000001".into()),
                Value::Utf8("2024-02-29 00:00:00.125001".into()),
            ],
            2,
            false,
        ),
        StoredRow::new(
            PrimaryKey::new(vec![KeyPart::Int64(3)]).expect("key"),
            vec![
                Value::Int64(3),
                Value::Int64(-1),
                Value::UInt64(9_007_199_254_740_993),
                Value::Utf8("-1".into()),
                Value::Utf8("0.000".into()),
                Value::float64(1.5),
                Value::Utf8("a ".into()),
                Value::Utf8("a".into()),
                Value::Binary(vec![0]),
                Value::Utf8("2024-03-31".into()),
                Value::Utf8("2024-03-31 00:00:00".into()),
                Value::Utf8("2024-03-31 00:00:00.125".into()),
                Value::Utf8("2024-03-31 00:00:00.125001".into()),
                Value::Utf8("-00:00:00.000001".into()),
                Value::Utf8("2024-03-31 00:00:00.125001".into()),
            ],
            3,
            false,
        ),
        StoredRow::new(
            PrimaryKey::new(vec![KeyPart::Int64(4)]).expect("key"),
            vec![
                Value::Int64(4),
                Value::Int64(0),
                Value::UInt64(9_223_372_036_854_775_808),
                Value::Utf8("0".into()),
                Value::Utf8("0.005".into()),
                Value::float64(2.5),
                Value::Utf8("a ".into()),
                Value::Utf8("a".into()),
                Value::Binary(vec![255]),
                Value::Utf8("2024-11-03".into()),
                Value::Utf8("2024-11-03 00:00:00".into()),
                Value::Utf8("2024-11-03 00:00:00.125".into()),
                Value::Utf8("2024-11-03 00:00:00.125001".into()),
                Value::Utf8("00:00:00.000000".into()),
                Value::Utf8("2024-11-03 00:00:00.125001".into()),
            ],
            4,
            false,
        ),
        StoredRow::new(
            PrimaryKey::new(vec![KeyPart::Int64(5)]).expect("key"),
            vec![
                Value::Int64(5),
                Value::Int64(1),
                Value::UInt64(18_446_744_073_709_551_615),
                Value::Utf8("1".into()),
                Value::Utf8("1.500".into()),
                Value::float64(-2.5),
                Value::Utf8("é".into()),
                Value::Utf8("é".into()),
                Value::Binary(vec![254]),
                Value::Utf8("2025-01-01".into()),
                Value::Utf8("2025-01-01 00:00:00".into()),
                Value::Utf8("2025-01-01 00:00:00.125".into()),
                Value::Utf8("2025-01-01 00:00:00.125001".into()),
                Value::Utf8("00:00:00.000001".into()),
                Value::Utf8("2025-01-01 00:00:00.125001".into()),
            ],
            5,
            false,
        ),
        StoredRow::new(
            PrimaryKey::new(vec![KeyPart::Int64(6)]).expect("key"),
            vec![
                Value::Int64(6),
                Value::Int64(9_007_199_254_740_993),
                Value::Null,
                Value::Utf8("2".into()),
                Value::Utf8("2.500".into()),
                Value::float64(10_000_000_000.0),
                Value::Utf8("e\u{301}".into()),
                Value::Utf8("e\u{301}".into()),
                Value::Binary(vec![97, 9, 98, 10, 99]),
                Value::Utf8("2025-12-31".into()),
                Value::Utf8("2025-12-31 00:00:00".into()),
                Value::Utf8("2025-12-31 00:00:00.125".into()),
                Value::Utf8("2025-12-31 00:00:00.125001".into()),
                Value::Utf8("100:00:00.000000".into()),
                Value::Utf8("2025-12-31 00:00:00.125001".into()),
            ],
            6,
            false,
        ),
        StoredRow::new(
            PrimaryKey::new(vec![KeyPart::Int64(7)]).expect("key"),
            vec![
                Value::Int64(7),
                Value::Int64(9_223_372_036_854_775_807),
                Value::UInt64(10),
                Value::Utf8("3".into()),
                Value::Utf8("99.995".into()),
                Value::float64(-0.0),
                Value::Utf8("a\tb\nc".into()),
                Value::Utf8("x".into()),
                Value::Binary(vec![97, 32]),
                Value::Utf8("2038-01-19".into()),
                Value::Utf8("2038-01-19 00:00:00".into()),
                Value::Utf8("2038-01-19 00:00:00.125".into()),
                Value::Utf8("2038-01-19 00:00:00.125001".into()),
                Value::Utf8("838:59:59.000000".into()),
                Value::Utf8("2038-01-19 00:00:00.125001".into()),
            ],
            7,
            false,
        ),
        StoredRow::new(
            PrimaryKey::new(vec![KeyPart::Int64(8)]).expect("key"),
            vec![
                Value::Int64(8),
                Value::Null,
                Value::UInt64(100),
                Value::Null,
                Value::Null,
                Value::Null,
                Value::Null,
                Value::Null,
                Value::Null,
                Value::Null,
                Value::Null,
                Value::Null,
                Value::Null,
                Value::Null,
                Value::Null,
            ],
            8,
            false,
        ),
    ]
}

#[allow(clippy::too_many_lines)]
pub fn cases() -> Vec<OracleCase> {
    vec![
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, n = 0 FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, n = '1' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, n = (SELECT MAX(n) FROM bounds WHERE id <= 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, n <=> 0 FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, n <=> '1' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, n <=> (SELECT MAX(n) FROM bounds WHERE id <= 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, n < 0 FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, n < '1' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, n < (SELECT MAX(n) FROM bounds WHERE id <= 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, n >= 0 FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, n >= '1' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, n >= (SELECT MAX(n) FROM bounds WHERE id <= 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, n <> 0 FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, n <> '1' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, n <> (SELECT MAX(n) FROM bounds WHERE id <= 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, n BETWEEN -1 AND 1 FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, n IN (0, 1, NULL) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, COALESCE(n, 0) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, CASE WHEN id % 2 = 0 THEN n ELSE 0 END FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, CAST(n AS CHAR) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, n = frac FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, u = 0 FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, u = '1' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, u = (SELECT MAX(n) FROM bounds WHERE id <= 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, u <=> 0 FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, u <=> '1' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, u <=> (SELECT MAX(n) FROM bounds WHERE id <= 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, u < 0 FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, u < '1' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, u < (SELECT MAX(n) FROM bounds WHERE id <= 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, u >= 0 FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, u >= '1' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, u >= (SELECT MAX(n) FROM bounds WHERE id <= 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, u <> 0 FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, u <> '1' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, u <> (SELECT MAX(n) FROM bounds WHERE id <= 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, u BETWEEN -1 AND 1 FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, u IN (0, 1, NULL) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, COALESCE(u, 0) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, CASE WHEN id % 2 = 0 THEN u ELSE 0 END FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, CAST(u AS CHAR) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, u = frac FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, whole = 0 FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, whole = '1' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, whole = (SELECT MAX(n) FROM bounds WHERE id <= 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, whole <=> 0 FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, whole <=> '1' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, whole <=> (SELECT MAX(n) FROM bounds WHERE id <= 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, whole < 0 FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, whole < '1' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, whole < (SELECT MAX(n) FROM bounds WHERE id <= 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, whole >= 0 FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, whole >= '1' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, whole >= (SELECT MAX(n) FROM bounds WHERE id <= 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, whole <> 0 FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, whole <> '1' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, whole <> (SELECT MAX(n) FROM bounds WHERE id <= 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, whole BETWEEN -1 AND 1 FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, whole IN (0, 1, NULL) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, COALESCE(whole, 0) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, CASE WHEN id % 2 = 0 THEN whole ELSE 0 END FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, CAST(whole AS CHAR) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, whole = frac FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, frac = 0 FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, frac = '1' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, frac = (SELECT MAX(n) FROM bounds WHERE id <= 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, frac <=> 0 FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, frac <=> '1' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, frac <=> (SELECT MAX(n) FROM bounds WHERE id <= 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, frac < 0 FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, frac < '1' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, frac < (SELECT MAX(n) FROM bounds WHERE id <= 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, frac >= 0 FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, frac >= '1' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, frac >= (SELECT MAX(n) FROM bounds WHERE id <= 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, frac <> 0 FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, frac <> '1' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, frac <> (SELECT MAX(n) FROM bounds WHERE id <= 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, frac BETWEEN -1 AND 1 FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, frac IN (0, 1, NULL) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, COALESCE(frac, 0) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, CASE WHEN id % 2 = 0 THEN frac ELSE 0 END FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, CAST(frac AS CHAR) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, frac = frac FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, approx = 0 FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, approx = '1' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, approx = (SELECT MAX(n) FROM bounds WHERE id <= 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, approx <=> 0 FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, approx <=> '1' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, approx <=> (SELECT MAX(n) FROM bounds WHERE id <= 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, approx < 0 FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, approx < '1' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, approx < (SELECT MAX(n) FROM bounds WHERE id <= 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, approx >= 0 FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, approx >= '1' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, approx >= (SELECT MAX(n) FROM bounds WHERE id <= 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, approx <> 0 FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, approx <> '1' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, approx <> (SELECT MAX(n) FROM bounds WHERE id <= 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, approx BETWEEN -1 AND 1 FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, approx IN (0, 1, NULL) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, COALESCE(approx, 0) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, CASE WHEN id % 2 = 0 THEN approx ELSE 0 END FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, CAST(approx AS CHAR) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, approx = frac FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, txt = 0 FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, txt = '1' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, txt = (SELECT MAX(n) FROM bounds WHERE id <= 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, txt <=> 0 FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, txt <=> '1' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, txt <=> (SELECT MAX(n) FROM bounds WHERE id <= 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, txt < 0 FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, txt < '1' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, txt < (SELECT MAX(n) FROM bounds WHERE id <= 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, txt >= 0 FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, txt >= '1' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, txt >= (SELECT MAX(n) FROM bounds WHERE id <= 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, txt <> 0 FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, txt <> '1' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, txt <> (SELECT MAX(n) FROM bounds WHERE id <= 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, txt BETWEEN -1 AND 1 FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, txt IN (0, 1, NULL) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, COALESCE(txt, 0) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, CASE WHEN id % 2 = 0 THEN txt ELSE 0 END FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, CAST(txt AS CHAR) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary conversion contexts", sql: "SELECT id, txt = frac FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary quantified subqueries", sql: "SELECT id, n IN (SELECT n FROM bounds WHERE id < 0) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary quantified subqueries", sql: "SELECT id, n NOT IN (SELECT n FROM bounds WHERE id < 0) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary quantified subqueries", sql: "SELECT id, n = ANY (SELECT n FROM bounds WHERE id < 0) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary quantified subqueries", sql: "SELECT id, n > ALL (SELECT n FROM bounds WHERE id < 0) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary quantified subqueries", sql: "SELECT id, n <> ALL (SELECT n FROM bounds WHERE id < 0) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary quantified subqueries", sql: "SELECT id, EXISTS (SELECT n FROM bounds WHERE id < 0) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary quantified subqueries", sql: "SELECT id, n IN (SELECT n FROM bounds WHERE id = 8) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary quantified subqueries", sql: "SELECT id, n NOT IN (SELECT n FROM bounds WHERE id = 8) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary quantified subqueries", sql: "SELECT id, n = ANY (SELECT n FROM bounds WHERE id = 8) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary quantified subqueries", sql: "SELECT id, n > ALL (SELECT n FROM bounds WHERE id = 8) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary quantified subqueries", sql: "SELECT id, n <> ALL (SELECT n FROM bounds WHERE id = 8) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary quantified subqueries", sql: "SELECT id, EXISTS (SELECT n FROM bounds WHERE id = 8) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary quantified subqueries", sql: "SELECT id, n IN (SELECT n FROM bounds WHERE id = 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary quantified subqueries", sql: "SELECT id, n NOT IN (SELECT n FROM bounds WHERE id = 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary quantified subqueries", sql: "SELECT id, n = ANY (SELECT n FROM bounds WHERE id = 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary quantified subqueries", sql: "SELECT id, n > ALL (SELECT n FROM bounds WHERE id = 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary quantified subqueries", sql: "SELECT id, n <> ALL (SELECT n FROM bounds WHERE id = 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary quantified subqueries", sql: "SELECT id, EXISTS (SELECT n FROM bounds WHERE id = 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary quantified subqueries", sql: "SELECT id, n IN (SELECT n FROM bounds WHERE id >= 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary quantified subqueries", sql: "SELECT id, n NOT IN (SELECT n FROM bounds WHERE id >= 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary quantified subqueries", sql: "SELECT id, n = ANY (SELECT n FROM bounds WHERE id >= 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary quantified subqueries", sql: "SELECT id, n > ALL (SELECT n FROM bounds WHERE id >= 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary quantified subqueries", sql: "SELECT id, n <> ALL (SELECT n FROM bounds WHERE id >= 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary quantified subqueries", sql: "SELECT id, EXISTS (SELECT n FROM bounds WHERE id >= 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary quantified subqueries", sql: "SELECT id, n IN (SELECT n FROM bounds WHERE id IN (4,5) UNION ALL SELECT n FROM bounds WHERE id = 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary quantified subqueries", sql: "SELECT id, n NOT IN (SELECT n FROM bounds WHERE id IN (4,5) UNION ALL SELECT n FROM bounds WHERE id = 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary quantified subqueries", sql: "SELECT id, n = ANY (SELECT n FROM bounds WHERE id IN (4,5) UNION ALL SELECT n FROM bounds WHERE id = 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary quantified subqueries", sql: "SELECT id, n > ALL (SELECT n FROM bounds WHERE id IN (4,5) UNION ALL SELECT n FROM bounds WHERE id = 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary quantified subqueries", sql: "SELECT id, n <> ALL (SELECT n FROM bounds WHERE id IN (4,5) UNION ALL SELECT n FROM bounds WHERE id = 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary quantified subqueries", sql: "SELECT id, EXISTS (SELECT n FROM bounds WHERE id IN (4,5) UNION ALL SELECT n FROM bounds WHERE id = 5) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary scalar cardinality", sql: "SELECT id, (SELECT n FROM bounds WHERE id < 0) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary scalar cardinality", sql: "SELECT id, (SELECT MAX(n) FROM bounds WHERE id < 0) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary scalar cardinality", sql: "SELECT a.id FROM bounds a WHERE EXISTS (SELECT 1 FROM bounds b WHERE b.n <=> a.n AND b.id <> a.id) ORDER BY a.id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary scalar cardinality", sql: "SELECT a.id, (SELECT COUNT(*) FROM bounds b WHERE b.frac < a.frac) FROM bounds a ORDER BY a.id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, txt FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, HEX(txt) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, LENGTH(txt) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, CHAR_LENGTH(txt) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, txt IS NULL FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, txt = 'a' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, txt = 'a ' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, txt LIKE 'a' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, txt IN ('a', 'a ', NULL) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, SUBSTRING(txt, -99) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, SUBSTRING(txt, 0) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, SUBSTRING(txt, 1, 0) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, LPAD(txt, 12, '') FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, RPAD(txt, 0, 'x') FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, CONCAT_WS(':', txt, 'end') FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, LOWER(txt) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, UPPER(txt) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, TRIM(txt) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string grouping", sql: "SELECT COUNT(DISTINCT txt) FROM bounds".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string grouping", sql: "SELECT MIN(txt), MAX(txt) FROM bounds".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string grouping", sql: "SELECT txt, COUNT(*) FROM bounds GROUP BY txt".into(), ordered: false },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, fixed FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, HEX(fixed) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, LENGTH(fixed) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, CHAR_LENGTH(fixed) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, fixed IS NULL FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, fixed = 'a' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, fixed = 'a ' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, fixed LIKE 'a' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, fixed IN ('a', 'a ', NULL) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, SUBSTRING(fixed, -99) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, SUBSTRING(fixed, 0) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, SUBSTRING(fixed, 1, 0) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, LPAD(fixed, 12, '') FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, RPAD(fixed, 0, 'x') FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, CONCAT_WS(':', fixed, 'end') FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, LOWER(fixed) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, UPPER(fixed) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, TRIM(fixed) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string grouping", sql: "SELECT COUNT(DISTINCT fixed) FROM bounds".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string grouping", sql: "SELECT MIN(fixed), MAX(fixed) FROM bounds".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string grouping", sql: "SELECT fixed, COUNT(*) FROM bounds GROUP BY fixed".into(), ordered: false },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, raw FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, HEX(raw) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, LENGTH(raw) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, CHAR_LENGTH(raw) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, raw IS NULL FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, raw = 'a' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, raw = 'a ' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, raw LIKE 'a' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, raw IN ('a', 'a ', NULL) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, SUBSTRING(raw, -99) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, SUBSTRING(raw, 0) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, SUBSTRING(raw, 1, 0) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, LPAD(raw, 12, '') FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, RPAD(raw, 0, 'x') FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, CONCAT_WS(':', raw, 'end') FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, LOWER(raw) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, UPPER(raw) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string storage", sql: "SELECT id, TRIM(raw) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string grouping", sql: "SELECT COUNT(DISTINCT raw) FROM bounds".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string grouping", sql: "SELECT MIN(raw), MAX(raw) FROM bounds".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary string grouping", sql: "SELECT raw, COUNT(*) FROM bounds GROUP BY raw".into(), ordered: false },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, day FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, DATE(day) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, YEAR(day) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, MONTH(day) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, DAYOFYEAR(day) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, LAST_DAY(day) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, DATE_ADD(day, INTERVAL 1 MONTH) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, DATE_SUB(day, INTERVAL 1 YEAR) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, day = '2024-02-29' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, day IN ('2024-02-29', NULL) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, TIMESTAMPDIFF(DAY, '2024-01-01', day) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, DATE_FORMAT(day, '%Y-%m-%d %H:%i:%s.%f') FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, dt0 FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, DATE(dt0) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, YEAR(dt0) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, MONTH(dt0) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, DAYOFYEAR(dt0) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, LAST_DAY(dt0) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, DATE_ADD(dt0, INTERVAL 1 MONTH) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, DATE_SUB(dt0, INTERVAL 1 YEAR) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, dt0 = '2024-02-29' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, dt0 IN ('2024-02-29', NULL) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, TIMESTAMPDIFF(DAY, '2024-01-01', dt0) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, DATE_FORMAT(dt0, '%Y-%m-%d %H:%i:%s.%f') FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, dt3 FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, DATE(dt3) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, YEAR(dt3) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, MONTH(dt3) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, DAYOFYEAR(dt3) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, LAST_DAY(dt3) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, DATE_ADD(dt3, INTERVAL 1 MONTH) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, DATE_SUB(dt3, INTERVAL 1 YEAR) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, dt3 = '2024-02-29' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, dt3 IN ('2024-02-29', NULL) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, TIMESTAMPDIFF(DAY, '2024-01-01', dt3) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, DATE_FORMAT(dt3, '%Y-%m-%d %H:%i:%s.%f') FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, dt6 FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, DATE(dt6) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, YEAR(dt6) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, MONTH(dt6) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, DAYOFYEAR(dt6) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, LAST_DAY(dt6) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, DATE_ADD(dt6, INTERVAL 1 MONTH) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, DATE_SUB(dt6, INTERVAL 1 YEAR) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, dt6 = '2024-02-29' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, dt6 IN ('2024-02-29', NULL) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, TIMESTAMPDIFF(DAY, '2024-01-01', dt6) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, DATE_FORMAT(dt6, '%Y-%m-%d %H:%i:%s.%f') FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, stamp FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, DATE(stamp) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, YEAR(stamp) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, MONTH(stamp) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, DAYOFYEAR(stamp) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, LAST_DAY(stamp) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, DATE_ADD(stamp, INTERVAL 1 MONTH) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, DATE_SUB(stamp, INTERVAL 1 YEAR) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, stamp = '2024-02-29' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, stamp IN ('2024-02-29', NULL) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, TIMESTAMPDIFF(DAY, '2024-01-01', stamp) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary temporal precision", sql: "SELECT id, DATE_FORMAT(stamp, '%Y-%m-%d %H:%i:%s.%f') FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary time durations", sql: "SELECT id, clock FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary time durations", sql: "SELECT id, TIME_TO_SEC(clock) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary time durations", sql: "SELECT id, clock < '00:00:00' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary time durations", sql: "SELECT id, clock BETWEEN '-100:00:00' AND '100:00:00' FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary time durations", sql: "SELECT id, clock + 0 FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary time durations", sql: "SELECT id, ADDTIME(clock, '00:00:00.000001') FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary time durations", sql: "SELECT id, SUBTIME(clock, '00:00:00.000001') FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary time durations", sql: "SELECT id, TIMEDIFF(clock, '00:00:00') FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary window carriers", sql: "SELECT id, COUNT(n) OVER (ORDER BY id), MIN(n) OVER (ORDER BY id), MAX(n) OVER (ORDER BY id) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary window carriers", sql: "SELECT id, COUNT(n) OVER (ORDER BY id ROWS BETWEEN 1 PRECEDING AND CURRENT ROW), MIN(n) OVER (ORDER BY id ROWS BETWEEN 1 PRECEDING AND CURRENT ROW), MAX(n) OVER (ORDER BY id ROWS BETWEEN 1 PRECEDING AND CURRENT ROW) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary window carriers", sql: "SELECT id, COUNT(n) OVER (ORDER BY id DESC ROWS BETWEEN CURRENT ROW AND 1 FOLLOWING), MIN(n) OVER (ORDER BY id DESC ROWS BETWEEN CURRENT ROW AND 1 FOLLOWING), MAX(n) OVER (ORDER BY id DESC ROWS BETWEEN CURRENT ROW AND 1 FOLLOWING) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary window carriers", sql: "SELECT id, COUNT(n) OVER (ORDER BY id RANGE BETWEEN CURRENT ROW AND CURRENT ROW), MIN(n) OVER (ORDER BY id RANGE BETWEEN CURRENT ROW AND CURRENT ROW), MAX(n) OVER (ORDER BY id RANGE BETWEEN CURRENT ROW AND CURRENT ROW) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary window carriers", sql: "SELECT id, COUNT(n) OVER (PARTITION BY id % 3), MIN(n) OVER (PARTITION BY id % 3), MAX(n) OVER (PARTITION BY id % 3) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary window carriers", sql: "SELECT id, COUNT(n) OVER (ORDER BY id ROWS BETWEEN 1 FOLLOWING AND 1 FOLLOWING), MIN(n) OVER (ORDER BY id ROWS BETWEEN 1 FOLLOWING AND 1 FOLLOWING), MAX(n) OVER (ORDER BY id ROWS BETWEEN 1 FOLLOWING AND 1 FOLLOWING) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary window carriers", sql: "SELECT id, COUNT(frac) OVER (ORDER BY id), MIN(frac) OVER (ORDER BY id), MAX(frac) OVER (ORDER BY id) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary window carriers", sql: "SELECT id, COUNT(frac) OVER (ORDER BY id ROWS BETWEEN 1 PRECEDING AND CURRENT ROW), MIN(frac) OVER (ORDER BY id ROWS BETWEEN 1 PRECEDING AND CURRENT ROW), MAX(frac) OVER (ORDER BY id ROWS BETWEEN 1 PRECEDING AND CURRENT ROW) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary window carriers", sql: "SELECT id, COUNT(frac) OVER (ORDER BY id DESC ROWS BETWEEN CURRENT ROW AND 1 FOLLOWING), MIN(frac) OVER (ORDER BY id DESC ROWS BETWEEN CURRENT ROW AND 1 FOLLOWING), MAX(frac) OVER (ORDER BY id DESC ROWS BETWEEN CURRENT ROW AND 1 FOLLOWING) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary window carriers", sql: "SELECT id, COUNT(frac) OVER (ORDER BY id RANGE BETWEEN CURRENT ROW AND CURRENT ROW), MIN(frac) OVER (ORDER BY id RANGE BETWEEN CURRENT ROW AND CURRENT ROW), MAX(frac) OVER (ORDER BY id RANGE BETWEEN CURRENT ROW AND CURRENT ROW) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary window carriers", sql: "SELECT id, COUNT(frac) OVER (PARTITION BY id % 3), MIN(frac) OVER (PARTITION BY id % 3), MAX(frac) OVER (PARTITION BY id % 3) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary window carriers", sql: "SELECT id, COUNT(frac) OVER (ORDER BY id ROWS BETWEEN 1 FOLLOWING AND 1 FOLLOWING), MIN(frac) OVER (ORDER BY id ROWS BETWEEN 1 FOLLOWING AND 1 FOLLOWING), MAX(frac) OVER (ORDER BY id ROWS BETWEEN 1 FOLLOWING AND 1 FOLLOWING) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary window carriers", sql: "SELECT id, COUNT(txt) OVER (ORDER BY id), MIN(txt) OVER (ORDER BY id), MAX(txt) OVER (ORDER BY id) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary window carriers", sql: "SELECT id, COUNT(txt) OVER (ORDER BY id ROWS BETWEEN 1 PRECEDING AND CURRENT ROW), MIN(txt) OVER (ORDER BY id ROWS BETWEEN 1 PRECEDING AND CURRENT ROW), MAX(txt) OVER (ORDER BY id ROWS BETWEEN 1 PRECEDING AND CURRENT ROW) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary window carriers", sql: "SELECT id, COUNT(txt) OVER (ORDER BY id DESC ROWS BETWEEN CURRENT ROW AND 1 FOLLOWING), MIN(txt) OVER (ORDER BY id DESC ROWS BETWEEN CURRENT ROW AND 1 FOLLOWING), MAX(txt) OVER (ORDER BY id DESC ROWS BETWEEN CURRENT ROW AND 1 FOLLOWING) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary window carriers", sql: "SELECT id, COUNT(txt) OVER (ORDER BY id RANGE BETWEEN CURRENT ROW AND CURRENT ROW), MIN(txt) OVER (ORDER BY id RANGE BETWEEN CURRENT ROW AND CURRENT ROW), MAX(txt) OVER (ORDER BY id RANGE BETWEEN CURRENT ROW AND CURRENT ROW) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary window carriers", sql: "SELECT id, COUNT(txt) OVER (PARTITION BY id % 3), MIN(txt) OVER (PARTITION BY id % 3), MAX(txt) OVER (PARTITION BY id % 3) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary window carriers", sql: "SELECT id, COUNT(txt) OVER (ORDER BY id ROWS BETWEEN 1 FOLLOWING AND 1 FOLLOWING), MIN(txt) OVER (ORDER BY id ROWS BETWEEN 1 FOLLOWING AND 1 FOLLOWING), MAX(txt) OVER (ORDER BY id ROWS BETWEEN 1 FOLLOWING AND 1 FOLLOWING) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary json identity", sql: "SELECT JSON_TYPE('null')".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary json identity", sql: "SELECT JSON_EXTRACT('null', '$')".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary json identity", sql: "SELECT JSON_EXTRACT('null', '$[last]')".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary json identity", sql: "SELECT JSON_LENGTH('null')".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary json identity", sql: "SELECT JSON_TYPE('\"NULL\"')".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary json identity", sql: "SELECT JSON_EXTRACT('\"NULL\"', '$')".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary json identity", sql: "SELECT JSON_EXTRACT('\"NULL\"', '$[last]')".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary json identity", sql: "SELECT JSON_LENGTH('\"NULL\"')".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary json identity", sql: "SELECT JSON_TYPE('9007199254740993')".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary json identity", sql: "SELECT JSON_EXTRACT('9007199254740993', '$')".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary json identity", sql: "SELECT JSON_EXTRACT('9007199254740993', '$[last]')".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary json identity", sql: "SELECT JSON_LENGTH('9007199254740993')".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary json identity", sql: "SELECT JSON_TYPE('1.00')".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary json identity", sql: "SELECT JSON_EXTRACT('1.00', '$')".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary json identity", sql: "SELECT JSON_EXTRACT('1.00', '$[last]')".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary json identity", sql: "SELECT JSON_LENGTH('1.00')".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary json identity", sql: "SELECT JSON_TYPE('[1,null,\"1\"]')".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary json identity", sql: "SELECT JSON_EXTRACT('[1,null,\"1\"]', '$')".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary json identity", sql: "SELECT JSON_EXTRACT('[1,null,\"1\"]', '$[last]')".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary json identity", sql: "SELECT JSON_LENGTH('[1,null,\"1\"]')".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary json identity", sql: "SELECT JSON_TYPE('{\"a\":1,\"a\":2}')".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary json identity", sql: "SELECT JSON_EXTRACT('{\"a\":1,\"a\":2}', '$')".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary json identity", sql: "SELECT JSON_EXTRACT('{\"a\":1,\"a\":2}', '$[last]')".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary json identity", sql: "SELECT JSON_LENGTH('{\"a\":1,\"a\":2}')".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary composition", sql: "SELECT id, JSON_OBJECT('n', n, 'd', frac, 'date', day, 'null', NULL) FROM bounds ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary composition", sql: "SELECT JSON_EXTRACT('[0,1,2,3]', '$[1 to last]')".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary composition", sql: "SELECT JSON_EXTRACT('{\"a\":{\"x\":1},\"b\":{\"x\":2}}', '$**.x')".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary composition", sql: "SELECT id, COUNT(*), MAX(frac) FROM bounds GROUP BY id ORDER BY id".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary result transport", sql: "SELECT NULL, 'NULL', '', X'00', X'FF', X'FE'".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary result transport", sql: "SELECT 'a\\tb', 'a\\nb', '__PINTAIL_CASE_1__'".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary result transport", sql: "SELECT SUBSTRING('abc', -9)".into(), ordered: true },
        OracleCase { sql_mode: "", family: "boundary result transport", sql: "SELECT LPAD('abc', 5, '')".into(), ordered: true },
    ]
}
