[package]
name = "pintail-sqllogic"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[dev-dependencies]
rand.workspace = true
sqlparser.workspace = true
mysql_async.workspace = true
tokio.workspace = true
serde.workspace = true
chrono.workspace = true
serde_json.workspace = true
sha2.workspace = true
pintail-catalog.workspace = true
pintail-exec.workspace = true
pintail-sql.workspace = true
pintail-store.workspace = true
pintail-types.workspace = true
tempfile.workspace = true
rustix.workspace = true

[lints]
workspace = true
