[package]
name = "pintail-exec"
description = "Planner, optimizer, and vectorized executor for Pintail"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
chrono.workspace = true
chrono-tz.workspace = true
icu_collator.workspace = true
md-5.workspace = true
pintail-catalog.workspace = true
pintail-sql.workspace = true
pintail-store.workspace = true
pintail-types.workspace = true
rand.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
sha1.workspace = true
sha2.workspace = true
crc32fast.workspace = true
tempfile.workspace = true
unicode-normalization.workspace = true
unicode-casefold.workspace = true
rayon.workspace = true

[lints]
workspace = true
