[package]
name = "pintail-exec"
description = "Planner, optimizer, and vectorized executor for Pintail"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
chrono.workspace = true
pintail-catalog.workspace = true
pintail-sql.workspace = true
pintail-store.workspace = true
pintail-types.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
