[package]
name = "pintail-meta"
description = "SQLite-backed control plane for Pintail"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
failpoints = ["pintail-failpoint/failpoints"]

[dependencies]
pintail-failpoint.workspace = true
anyhow.workspace = true
rusqlite.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
