#!/bin/sh
# Pintail installer for a Linux server.
#
#   curl -fsSL https://raw.githubusercontent.com/chittihq/pintail/dev/scripts/install.sh | sh
#
# Installs Docker and the Compose plugin when they are missing, writes a
# default docker-compose.yml under /opt/pintail, starts Pintail from the
# published image, and prints where to go next. Safe to run again: an
# existing installation is upgraded to the requested version and its
# configuration is left alone.
#
# Settings, all optional, read from the environment:
#   PINTAIL_VERSION    release to install (default: the latest GitHub release)
#   PINTAIL_DIR        where the compose file lives (default: /opt/pintail)
#   PINTAIL_HTTP_PORT  dashboard and HTTP API port (default: 8080)
#   PINTAIL_WIRE_PORT  MySQL wire port (default: 3306)

set -eu

REPO="chittihq/pintail"
IMAGE="ghcr.io/${REPO}"
FALLBACK_VERSION="0.1.0"
PINTAIL_DIR="${PINTAIL_DIR:-/opt/pintail}"
PINTAIL_HTTP_PORT="${PINTAIL_HTTP_PORT:-8080}"
PINTAIL_WIRE_PORT="${PINTAIL_WIRE_PORT:-3306}"

say() { printf '%s\n' "$*"; }
fail() { printf 'install: %s\n' "$*" >&2; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }

# Root, or sudo for the steps that need it.
if [ "$(id -u)" -eq 0 ]; then
  SUDO=""
elif have sudo; then
  SUDO="sudo"
else
  fail "run as root, or install sudo"
fi

[ "$(uname -s)" = "Linux" ] || fail "this installer targets Linux; on macOS or Windows install Docker Desktop and use the compose file from the README"

have curl || fail "curl is required"

# 1. Docker Engine.
if ! have docker; then
  say "Installing Docker Engine ..."
  curl -fsSL https://get.docker.com | $SUDO sh
fi
if have systemctl; then
  $SUDO systemctl enable --now docker >/dev/null 2>&1 || true
fi
$SUDO docker info >/dev/null 2>&1 || fail "Docker is installed but the daemon is not reachable"

# 2. The Compose plugin, which get.docker.com installs on the distributions
#    it supports; older or unusual hosts may need it separately.
if ! $SUDO docker compose version >/dev/null 2>&1; then
  say "Installing the Docker Compose plugin ..."
  if have apt-get; then
    $SUDO apt-get install -y docker-compose-plugin
  elif have dnf; then
    $SUDO dnf install -y docker-compose-plugin
  elif have yum; then
    $SUDO yum install -y docker-compose-plugin
  else
    fail "could not install the Docker Compose plugin; see https://docs.docker.com/compose/install/"
  fi
  $SUDO docker compose version >/dev/null 2>&1 || fail "the Docker Compose plugin did not install"
fi

# 3. The version: the latest release unless one was named.
if [ -z "${PINTAIL_VERSION:-}" ]; then
  PINTAIL_VERSION="$(curl -fsSL "https://api.github.com/repos/${REPO}/releases/latest" 2>/dev/null \
    | sed -n 's/.*"tag_name": *"v\{0,1\}\([^"]*\)".*/\1/p' | head -n 1)"
  [ -n "$PINTAIL_VERSION" ] || PINTAIL_VERSION="$FALLBACK_VERSION"
fi
PINTAIL_VERSION="${PINTAIL_VERSION#v}"

# 4. The compose file, written once; a later run keeps the operator's edits
#    and only moves the image tag.
$SUDO mkdir -p "$PINTAIL_DIR"
COMPOSE="$PINTAIL_DIR/docker-compose.yml"
if [ -f "$COMPOSE" ]; then
  say "Keeping the existing $COMPOSE; setting the image to ${IMAGE}:${PINTAIL_VERSION}"
  $SUDO sed -i "s#image: ${IMAGE}:.*#image: ${IMAGE}:${PINTAIL_VERSION}#" "$COMPOSE"
else
  say "Writing $COMPOSE"
  $SUDO tee "$COMPOSE" >/dev/null <<YAML
# Generated by the Pintail installer. Edit freely; re-running the installer
# only updates the image tag. The repository's docker-compose.yml documents
# every setting: https://github.com/${REPO}/blob/dev/docker-compose.yml
name: pintail

services:
  pintail:
    image: ${IMAGE}:${PINTAIL_VERSION}
    ports:
      - "${PINTAIL_HTTP_PORT}:8080"   # dashboard and HTTP API
      - "${PINTAIL_WIRE_PORT}:3306"   # MySQL wire endpoint
    environment:
      PINTAIL_BUILD_VERSION: "${PINTAIL_VERSION}"
      PINTAIL_DATA_DIR: /var/lib/pintail
    volumes:
      - pintail-data:/var/lib/pintail
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "http://127.0.0.1:8080/health"]
      interval: 5s
      timeout: 2s
      retries: 12
      start_period: 30s
    restart: unless-stopped

volumes:
  pintail-data:
YAML
fi

# 5. Start it.
say "Starting Pintail ${PINTAIL_VERSION} ..."
$SUDO docker compose -f "$COMPOSE" pull --quiet
$SUDO docker compose -f "$COMPOSE" up --detach

attempt=0
until curl -fsS "http://127.0.0.1:${PINTAIL_HTTP_PORT}/health" >/dev/null 2>&1; do
  attempt=$((attempt + 1))
  [ "$attempt" -lt 60 ] || fail "Pintail did not report healthy within two minutes; inspect with: docker compose -f $COMPOSE logs pintail"
  sleep 2
done

say ""
say "Pintail ${PINTAIL_VERSION} is running."
say ""
say "  Dashboard:  http://$(hostname -I 2>/dev/null | awk '{print $1}' || echo 127.0.0.1):${PINTAIL_HTTP_PORT}"
say "  MySQL:      port ${PINTAIL_WIRE_PORT}"
say "  Config:     $COMPOSE"
say "  Data:       docker volume pintail_pintail-data"
say ""
# The first boot prints its generated secrets once; surface them here so
# they are not lost in a log nobody read.
if $SUDO docker compose -f "$COMPOSE" logs pintail 2>/dev/null | grep -q "first boot"; then
  say "First-boot secrets (shown once by the server, keep them safe):"
  $SUDO docker compose -f "$COMPOSE" logs --no-log-prefix pintail 2>/dev/null \
    | grep -E "PINTAIL_(JWT_SECRET|DSN_ENCRYPTION_KEY)=" | sed 's/^/  /'
  say ""
fi
say "Open the dashboard, create the first admin, and add your MySQL database."
say "Logs: docker compose -f $COMPOSE logs -f pintail"
