[package]
name = "pintail-wire"
description = "Read-only MySQL wire protocol server for Pintail"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
rcgen.workspace = true
pintail-log.workspace = true
anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
pintail-catalog.workspace = true
pintail-cdc.workspace = true
pintail-exec.workspace = true
pintail-meta.workspace = true
pintail-probe.workspace = true
pintail-protocol.workspace = true
pintail-sql.workspace = true
pintail-store.workspace = true
pintail-types.workspace = true
pintail-write.workspace = true
rand.workspace = true
rustls-pemfile.workspace = true
tokio-rustls.workspace = true
serde_json.workspace = true
sha1.workspace = true
rsa.workspace = true
rand_core06.workspace = true
sha2.workspace = true
tokio = { workspace = true, features = ["io-util"] }
thiserror.workspace = true

[lints]
workspace = true

[dev-dependencies]
pintail-write.workspace = true
mysql_async.workspace = true
rustls.workspace = true
tempfile.workspace = true
