[package]
name = "pintail-wire"
description = "Read-only MySQL wire protocol server for Pintail"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
opensrv-mysql.workspace = true
pintail-catalog.workspace = true
pintail-cdc.workspace = true
pintail-exec.workspace = true
pintail-meta.workspace = true
pintail-probe.workspace = true
pintail-sql.workspace = true
pintail-store.workspace = true
pintail-types.workspace = true
rand.workspace = true
rustls-pemfile.workspace = true
tokio-rustls.workspace = true
serde_json.workspace = true
sha1.workspace = true
tokio.workspace = true
thiserror.workspace = true

[lints]
workspace = true

[dev-dependencies]
mysql_async.workspace = true
rcgen.workspace = true
rustls.workspace = true
sha2.workspace = true
tempfile.workspace = true
