[package]
name = "pintail-probe"
description = "MySQL source capability probing for Pintail"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
pintail-log.workspace = true
mysql_async.workspace = true
pintail-types.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
tokio.workspace = true

[lints]
workspace = true
